language: node_js
node_js:
  - "0.12"
services:
  - redis-server
after_success:
  - NODE_ENV=test ./node_modules/.bin/mocha --require blanket --reporter mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js